namespace SirketMotoru.CanliPano;

internal static class YazilimBorsasiHtml
{
    public const string Icerik = """
<!doctype html>
<html lang="tr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Yazılım Borsası · Canlı Piyasa</title>
<style>
:root{color-scheme:dark;--bg:#050812;--panel:#0b1220;--panel2:#101a2c;--line:#20304a;--text:#edf4ff;--muted:#8fa2bf;--green:#39e5a4;--red:#ff6678;--yellow:#ffd166;--blue:#59a8ff;--purple:#b78dff;--cyan:#42d5ef;--shadow:0 18px 50px #0007}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:radial-gradient(circle at 8% 0,#10264a 0,transparent 33%),radial-gradient(circle at 92% 4%,#21154a 0,transparent 28%),var(--bg);color:var(--text);font-family:Inter,Segoe UI,Arial,sans-serif}body{padding:14px}.shell{max-width:2000px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:15px 17px;border:1px solid var(--line);border-radius:18px;background:#0a1322e8;box-shadow:var(--shadow);position:sticky;top:8px;z-index:20;backdrop-filter:blur(14px)}.brand{display:flex;align-items:center;gap:12px}.logo{width:47px;height:47px;border-radius:14px;background:linear-gradient(135deg,var(--green),var(--blue),var(--purple));display:grid;place-items:center;color:#04131a;font-weight:1000}.brand h1{margin:0;font-size:20px}.sub{color:var(--muted);font-size:11px;margin-top:3px}.status{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.pill{border:1px solid var(--line);background:#091425;padding:7px 10px;border-radius:999px;font-size:11px;color:var(--muted)}.pill b{color:var(--text)}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--yellow);margin-right:6px}.dot.ok{background:var(--green);box-shadow:0 0 12px var(--green)}.dot.bad{background:var(--red)}
.tabs{display:flex;gap:7px;flex-wrap:wrap;margin:13px 0}.tab{border:1px solid var(--line);background:#091322;color:var(--muted);border-radius:999px;padding:8px 12px;cursor:pointer;font-weight:700}.tab.active{background:linear-gradient(135deg,var(--green),var(--blue));color:#04131a;border-color:transparent}.page{display:none}.page.active{display:block}.grid{display:grid;gap:12px}.kpis{grid-template-columns:repeat(8,minmax(130px,1fr));margin-bottom:12px}.card{background:linear-gradient(180deg,#101b2eeb,#08101deb);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);overflow:hidden}.kpi{padding:14px;min-height:103px;position:relative}.kpi:after{content:"";position:absolute;width:90px;height:90px;border-radius:50%;right:-35px;bottom:-50px;background:var(--a,var(--blue));filter:blur(34px);opacity:.25}.label{font-size:10px;letter-spacing:.11em;text-transform:uppercase;color:var(--muted)}.value{font-size:23px;font-weight:900;margin-top:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.note{font-size:10px;color:var(--muted);margin-top:7px}.head{padding:13px 15px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:10px}.title{font-size:13px;font-weight:900;letter-spacing:.05em}.section-note{font-size:10px;color:var(--muted)}
.market-layout{grid-template-columns:minmax(0,1.55fr) minmax(350px,.65fr);align-items:start}.stack{display:grid;gap:12px}.company-grid{display:grid;grid-template-columns:repeat(4,minmax(260px,1fr));gap:10px;padding:11px}.company{background:#081220;border:1px solid var(--line);border-radius:14px;padding:13px;position:relative;overflow:hidden}.company:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--c,var(--blue))}.company-top{display:flex;justify-content:space-between;gap:10px}.company-name{font-weight:900;font-size:17px}.company-id{font-size:9px;color:var(--muted);margin-top:3px}.rank{font-weight:1000;font-size:20px;color:var(--yellow)}.state{display:inline-block;margin-top:6px;font-size:9px;padding:4px 7px;border:1px solid #24634f;border-radius:999px;color:var(--green)}.state.off{border-color:#6b3040;color:var(--red)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.metric{padding:8px;background:#0d192a;border:1px solid #1b2940;border-radius:9px;min-width:0}.metric span{display:block;color:var(--muted);font-size:8px;text-transform:uppercase}.metric b{display:block;font-size:12px;margin-top:4px;overflow:hidden;text-overflow:ellipsis}.bars{display:grid;gap:6px;margin-top:10px}.barrow{display:grid;grid-template-columns:68px 1fr 31px;gap:6px;align-items:center;font-size:9px;color:var(--muted)}.bar{height:6px;background:#162339;border-radius:99px;overflow:hidden}.bar i{height:100%;display:block;background:linear-gradient(90deg,var(--blue),var(--green))}.chips{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px}.chip{font-size:8px;padding:4px 6px;border:1px solid #253751;border-radius:7px;color:#bbcae0;background:#0c1728}.chip.good{border-color:#245d4d;color:var(--green)}.chip.bad{border-color:#743546;color:var(--red)}
.tablewrap{overflow:auto;max-height:650px}table{width:100%;border-collapse:collapse;min-width:900px;font-size:11px}th{position:sticky;top:0;background:#101b2e;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em;text-align:left;padding:10px;border-bottom:1px solid var(--line);z-index:2}td{padding:10px;border-bottom:1px solid #1b2a41;vertical-align:top}tr:hover td{background:#54a8ff0b}.num{text-align:right;font-variant-numeric:tabular-nums}.good{color:var(--green)}.bad{color:var(--red)}.warn{color:var(--yellow)}.muted{color:var(--muted)}.name{font-weight:800}.small{font-size:9px;color:var(--muted);margin-top:3px}.progress{height:7px;background:#152238;border-radius:99px;overflow:hidden;min-width:90px}.progress i{display:block;height:100%;background:linear-gradient(90deg,var(--purple),var(--cyan))}.summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:11px}.log{height:630px;overflow:auto;padding:8px 10px;background:#050a12;font:10px/1.45 Consolas,monospace}.logline{display:grid;grid-template-columns:62px 64px 1fr;gap:7px;border-bottom:1px dashed #1a2639;padding:4px 0}.level{font-weight:800}.level.HATA{color:var(--red)}.level.UYARI{color:var(--yellow)}.level.BASARILI{color:var(--green)}.level.TICK{color:var(--purple)}.level.BILGI{color:var(--cyan)}.chart{height:270px;padding:10px}canvas{width:100%;height:100%;display:block}.empty{padding:24px;text-align:center;color:var(--muted)}.two{grid-template-columns:1fr 1fr}.footer{text-align:center;color:var(--muted);font-size:9px;padding:13px}
@media(max-width:1600px){.kpis{grid-template-columns:repeat(4,1fr)}.company-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:1200px){.market-layout{grid-template-columns:1fr}.company-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){body{padding:7px}.top{position:static;align-items:flex-start;flex-direction:column}.status{justify-content:flex-start}.kpis{grid-template-columns:repeat(2,1fr)}.company-grid,.two{grid-template-columns:1fr}.summary-grid{grid-template-columns:repeat(2,1fr)}.metrics{grid-template-columns:repeat(2,1fr)}.log{height:440px}}
</style>
</head>
<body>
<div class="shell">
<header class="top"><div class="brand"><div class="logo">YB</div><div><h1>Yazılım Borsası</h1><div class="sub">Şirket değeri · uygulamalar · abonelikler · protokoller · hizmetler · finans · güvenlik</div></div></div><div class="status"><span class="pill"><i id="dot" class="dot"></i><b id="connection">BAĞLANIYOR</b></span><span class="pill">Motor <b id="motor">—</b></span><span class="pill">Tick <b id="tick">0</b></span><span class="pill">Borsa <b id="version">—</b></span><span class="pill" id="clock">—</span></div></header>
<nav class="tabs"><button class="tab active" data-page="overview">Genel Borsa</button><button class="tab" data-page="apps">Uygulamalar</button><button class="tab" data-page="protocols">Protokoller</button><button class="tab" data-page="services">Hizmetler</button><button class="tab" data-page="finance">Finans & Banka</button><button class="tab" data-page="operations">Sözleşmeler & Yatırımlar</button><button class="tab" data-page="security">Güvenlik & Akış</button></nav>
<section class="grid kpis">
<div class="card kpi" style="--a:var(--purple)"><div class="label">Toplam şirket değeri</div><div id="totalValue" class="value">₺0</div><div id="valueNote" class="note">Piyasa hazırlanıyor</div></div>
<div class="card kpi" style="--a:var(--green)"><div class="label">Toplam kasa</div><div id="totalCash" class="value">₺0</div><div id="incomeNote" class="note">₺0 net gelir</div></div>
<div class="card kpi" style="--a:var(--red)"><div class="label">Toplam borç</div><div id="totalDebt" class="value">₺0</div><div id="debtNote" class="note">Aktif krediler</div></div>
<div class="card kpi" style="--a:var(--cyan)"><div class="label">Toplam abone</div><div id="totalSubs" class="value">0</div><div id="subNote" class="note">Uygulama müşterileri</div></div>
<div class="card kpi" style="--a:var(--blue)"><div class="label">Uygulamalar</div><div id="appCount" class="value">0 / 0</div><div class="note">Piyasada / kodlanmış</div></div>
<div class="card kpi" style="--a:var(--yellow)"><div class="label">Özel protokoller</div><div id="protocolCount" class="value">0 / 0</div><div class="note">Piyasada / kodlanmış</div></div>
<div class="card kpi" style="--a:var(--green)"><div class="label">Bağlı şirket</div><div id="connected" class="value">0 / 0</div><div id="serviceNote" class="note">0 hizmet</div></div>
<div class="card kpi" style="--a:var(--red)"><div class="label">Siber olay</div><div id="attackCount" class="value">0 / 0</div><div id="lossNote" class="note">₺0 kayıp</div></div>
</section>

<section id="overview" class="page active"><div class="grid market-layout"><div class="stack"><section class="card"><div class="head"><div><div class="title">ŞİRKET DEĞER LİSTESİ</div><div class="section-note">Şirket değeri, hisse tahmini, finans, kalite ve ürün ekosistemi</div></div><div id="updated" class="section-note">—</div></div><div id="companies" class="company-grid"></div></section><section class="card"><div class="head"><div><div class="title">ŞİRKET DEĞERİ VE KASA GRAFİĞİ</div><div class="section-note">Tarayıcı açık kaldığı sürece son 120 örnek</div></div></div><div class="chart"><canvas id="chart"></canvas></div></section></div><aside class="stack"><section class="card"><div class="head"><div class="title">SON TICK</div></div><div id="tickSummary" class="summary-grid"></div></section><section class="card"><div class="head"><div class="title">EN DEĞERLİ UYGULAMALAR</div></div><div id="topApps" class="tablewrap"></div></section></aside></div></section>

<section id="apps" class="page"><section class="card"><div class="head"><div><div class="title">UYGULAMA VE ABONELİK PAZARI</div><div class="section-note">Teknik manifest, ticari yayın, fiyat, kullanıcı kapasitesi, memnuniyet ve gelir</div></div></div><div class="tablewrap"><table><thead><tr><th>Uygulama</th><th>Şirket</th><th>Kategori</th><th>Teknik</th><th>Ticari</th><th>Model</th><th class="num">Abonelik</th><th class="num">Kullanım</th><th>Kullanıcı / Kapasite</th><th class="num">Kalite</th><th class="num">Memnuniyet</th><th class="num">Gelir</th><th>Protokoller</th></tr></thead><tbody id="appsBody"></tbody></table></div></section></section>
<section id="protocols" class="page"><section class="card"><div class="head"><div><div class="title">ÖZEL PROTOKOL PİYASASI</div><div class="section-note">Kodlanmış yetkinlikler, şemalar, uyumluluk ve ticari lisans durumu</div></div></div><div class="tablewrap"><table><thead><tr><th>Protokol</th><th>Sahip</th><th>Sürüm</th><th>Şema</th><th>Teknik</th><th>Ticari</th><th>Yetkinlikler</th><th>Uyumlu protokoller</th><th>Piyasa kimliği</th></tr></thead><tbody id="protocolsBody"></tbody></table></div></section></section>
<section id="services" class="page"><section class="card"><div class="head"><div><div class="title">TEMEL HİZMET PİYASASI</div><div class="section-note">Talep, saldırı, zorluk, fiyat ve sağlayıcı kalitesi</div></div></div><div class="tablewrap"><table><thead><tr><th>Hizmet</th><th>Durum</th><th class="num">Talep</th><th class="num">Şüpheli</th><th class="num">Zorluk</th><th class="num">Bütçe</th><th class="num">En ucuz</th><th class="num">En pahalı</th><th class="num">Sağlayıcı</th><th>Şirket teklifleri</th></tr></thead><tbody id="servicesBody"></tbody></table></div></section></section>
<section id="finance" class="page"><div class="grid two"><section class="card"><div class="head"><div><div class="title">ŞİRKET FİNANS TABLOSU</div><div class="section-note">Değer, hisse tahmini, kasa, borç, kredi notu ve işletme gelirleri</div></div></div><div class="tablewrap"><table><thead><tr><th>Şirket</th><th class="num">Değer</th><th class="num">Hisse</th><th class="num">Kasa</th><th class="num">Borç</th><th class="num">Kredi notu</th><th class="num">Abonelik geliri</th><th class="num">Ürün geliri</th><th class="num">İşletme gideri</th><th class="num">Finansman gideri</th></tr></thead><tbody id="financeBody"></tbody></table></div></section><section class="card"><div class="head"><div><div class="title">AKTİF KREDİLER</div><div class="section-note">Taksit, kalan borç, faiz ve gecikme</div></div></div><div class="tablewrap"><table><thead><tr><th>Şirket</th><th>Tür</th><th class="num">Ana para</th><th class="num">Kalan borç</th><th class="num">Taksit</th><th class="num">Kalan</th><th class="num">Faiz/tick</th><th class="num">Gecikme</th><th>Durum</th></tr></thead><tbody id="creditsBody"></tbody></table></div></section></div></section>
<section id="operations" class="page"><div class="grid two"><section class="card"><div class="head"><div><div class="title">SLA SÖZLEŞMELERİ</div><div class="section-note">Süre, ödeme, ihlal ve teknik şartlar</div></div></div><div class="tablewrap"><table><thead><tr><th>Şirket</th><th>Sözleşme</th><th>Kategori</th><th>Tick aralığı</th><th class="num">Tick ödeme</th><th class="num">İhlal cezası</th><th class="num">Başarılı</th><th class="num">İhlal</th><th>Durum</th></tr></thead><tbody id="contractsBody"></tbody></table></div></section><section class="card"><div class="head"><div><div class="title">ALTYAPI YATIRIMLARI</div><div class="section-note">CPU, RAM, ağ, depolama, güvenlik, Ar-Ge ve ekipler</div></div></div><div class="tablewrap"><table><thead><tr><th>Şirket</th><th>Yatırım</th><th class="num">Seviye</th></tr></thead><tbody id="investmentsBody"></tbody></table></div></section></div></section>
<section id="security" class="page"><div class="grid market-layout"><section class="card"><div class="head"><div><div class="title">GÜVENLİK SKOR TABLOSU</div><div class="section-note">Engellenen ve başarılı saldırılar, kayıp ve güvenlik puanı</div></div></div><div class="tablewrap"><table><thead><tr><th>Şirket</th><th class="num">Güvenlik</th><th class="num">Kod kalitesi</th><th class="num">Engellenen</th><th class="num">Başarılı saldırı</th><th class="num">Finansal kayıp</th><th>Risk</th></tr></thead><tbody id="securityBody"></tbody></table></div></section><section class="card"><div class="head"><div><div class="title">CANLI MOTOR AKIŞI</div><div class="section-note">Son 300 olay</div></div></div><div id="logs" class="log"></div></section></div></section>
<div class="footer">8080 salt-okunur piyasa ekranıdır · İşletme kararları 8090 üzerinden, kodlama şirket sunucularında yapılır</div>
</div>
<script>
const S={history:new Map(),data:null};const money=new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:2});const num=new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2});const integer=new Intl.NumberFormat("tr-TR",{maximumFractionDigits:0});const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));const pct=v=>`${num.format(Number(v||0))}%`;const m=v=>money.format(Number(v||0));const n=v=>num.format(Number(v||0));const i=v=>integer.format(Number(v||0));const bool=v=>v===true;const text=(id,v)=>document.getElementById(id).textContent=v;const color=index=>["#39e5a4","#59a8ff","#b78dff","#ffd166","#42d5ef","#ff6678"][index%6];
function metric(label,value,cls=""){return `<div class="metric"><span>${esc(label)}</span><b class="${cls}">${esc(value)}</b></div>`}function bar(label,value){const v=Math.max(0,Math.min(100,Number(value||0)));return `<div class="barrow"><span>${esc(label)}</span><div class="bar"><i style="width:${v}%"></i></div><b>${n(v)}</b></div>`}function chip(v,cls=""){return `<span class="chip ${cls}">${esc(v)}</span>`}function appProduct(a){return a?.urun||null}function isActiveProduct(a){const u=appProduct(a);return bool(a?.piyasada)&&u&&bool(u.aktif)}
function render(data){S.data=data;const g=data.genel||{},p=data.piyasa||{},o=p.islemeOzeti||{};text("motor",data.motor?.motorKimligi||"—");text("tick",data.motor?.tickNumarasi??0);text("version",data.motor?.borsaSurumu||"—");text("updated",new Date(data.motor?.sunucuZamani||Date.now()).toLocaleString("tr-TR"));text("totalValue",m(g.toplamSirketDegeri));text("valueNote",`${i(g.toplamSirketSayisi)} şirket · ${i(g.teknikUygulamaSayisi)} teknik uygulama`);text("totalCash",m(g.toplamSirketKasasi));text("incomeNote",`${m(g.toplamNetGelir)} toplam net gelir`);text("totalDebt",m(g.toplamBorc));text("debtNote",`${i((data.krediPiyasasi||[]).filter(x=>x.kredi?.aktif).length)} aktif kredi`);text("totalSubs",i(g.toplamAbone));text("subNote",`${i(g.aktifMusteriSayisi)} aktif pazar müşterisi`);text("appCount",`${i(g.piyasadakiUygulamaSayisi)} / ${i(g.teknikUygulamaSayisi)}`);text("protocolCount",`${i(g.piyasadakiProtokolSayisi)} / ${i(g.teknikProtokolSayisi)}`);text("connected",`${i(g.bagliSirketSayisi)} / ${i(g.toplamSirketSayisi)}`);text("serviceNote",`${i(g.toplamHizmetIlani)} toplam hizmet ilanı`);text("attackCount",`${i(g.toplamEngellenenSaldiri)} / ${i(g.toplamBasariliSaldiri)}`);text("lossNote",`${m(g.toplamGuvenlikKaybi)} güvenlik kaybı`);renderCompanies(data.sirketler||[]);renderApps(data.uygulamaPiyasasi||[]);renderProtocols(data.protokolPiyasasi||[]);renderServices(data.hizmetPiyasasi||[]);renderFinance(data.sirketler||[]);renderCredits(data.krediPiyasasi||[]);renderContracts(data.sozlesmePiyasasi||[]);renderInvestments(data.yatirimPiyasasi||[]);renderSecurity(data.sirketler||[]);renderSummary(o);renderLogs(data.olaylar||[]);updateHistory(data.sirketler||[]);drawChart();renderTopApps(data.uygulamaPiyasasi||[])}
function renderCompanies(list){const el=document.getElementById("companies");const sorted=[...list].sort((a,b)=>Number(b.isletim?.sirketDegeri||0)-Number(a.isletim?.sirketDegeri||0));if(!sorted.length){el.innerHTML='<div class="empty">Şirket bulunamadı.</div>';return}el.innerHTML=sorted.map((c,index)=>{const op=c.isletim||{},apps=(c.kodTabanliYayinlar?.uygulamalar||[]),protocols=(c.kodTabanliYayinlar?.protokoller||[]),invest=Object.entries(op.yatirimSeviyeleri||{}).filter(([,v])=>Number(v)>0);return `<article class="company" style="--c:${color(index)}"><div class="company-top"><div><div class="company-name">${esc(c.sirketAdi)}</div><div class="company-id">${esc(c.sirketKimligi)} · ${esc(c.sunucuAdresi)}:${esc(c.sunucuPortu)} · v${esc(c.sunucuSurumu||"—")}</div><span class="state ${c.bagli?"":"off"}">${c.bagli?"BAĞLI":"ÇEVRİMDIŞI"}</span></div><div class="rank">#${index+1}</div></div><div class="metrics">${metric("Şirket değeri",m(op.sirketDegeri),"good")}${metric("Hisse tahmini",m(op.tahminiHisseFiyati))}${metric("Kasa",m(c.kasa),"good")}${metric("Borç",m(op.toplamBorc),Number(op.toplamBorc)>0?"warn":"")}${metric("Abone",i(op.toplamAboneSayisi))}${metric("Kredi notu",i(op.krediNotu))}${metric("Uygulama",`${apps.filter(x=>x.piyasada).length}/${apps.length}`)}${metric("Protokol",`${protocols.filter(x=>x.piyasada).length}/${protocols.length}`)}${metric("Gecikme",`${n(c.sonGecikmeMs)} ms`)}</div><div class="bars">${bar("Kod",c.kodKalitesiPuani)}${bar("Performans",c.performansPuani)}${bar("Güvenlik",c.guvenlikPuani)}${bar("İtibar",c.itibarPuani)}${bar("Güvenilir",c.guvenilirlikPuani)}${bar("Memnuniyet",c.ortalamaMusteriMemnuniyeti)}</div><div class="chips">${apps.map(x=>chip(`${x.uygulama?.uygulamaAdi||x.uygulama?.uygulamaKimligi} ${x.piyasada?"●":"○"}`,x.piyasada?"good":"")).join("")}${protocols.map(x=>chip(`${x.protokol?.protokolAdi||x.protokol?.protokolKimligi} ${x.piyasada?"●":"○"}`,x.piyasada?"good":"")).join("")}${invest.map(([k,v])=>chip(`${k} L${v}`)).join("")}</div></article>`}).join("")}
function renderApps(list){const body=document.getElementById("appsBody");if(!list.length){body.innerHTML='<tr><td colspan="13" class="empty">Kodlanmış uygulama yok.</td></tr>';return}body.innerHTML=[...list].sort((a,b)=>Number(appProduct(b)?.toplamGelir||0)-Number(appProduct(a)?.toplamGelir||0)).map(a=>{const app=a.uygulama||{},d=a.dogrulama||{},u=appProduct(a),active=isActiveProduct(a),capacity=Number(u?.kullaniciKapasitesi||0),users=Number(u?.aktifKullaniciSayisi||0),ratio=capacity?Math.min(100,users/capacity*100):0;return `<tr><td><div class="name">${esc(app.uygulamaAdi||app.uygulamaKimligi)}</div><div class="small">${esc(app.uygulamaKimligi)} · v${esc(app.surum||"—")} · ${(app.ozellikler||[]).length} özellik</div></td><td>${esc(a.sirketAdi)}</td><td>${esc(app.kategori||"—")}</td><td class="${d.gecerli?"good":"bad"}">${d.gecerli?"STANDARDI GEÇTİ":"EKSİK"}<div class="small">${esc(d.durum||"")}</div></td><td class="${active?"good":a.piyasada?"warn":"muted"}">${active?"YAYINDA":a.piyasada?"DURDURULDU":"8090 BEKLİYOR"}</td><td>${esc(u?.fiyatlandirmaModeli||"—")}</td><td class="num">${u?m(u.abonelikUcreti):"—"}</td><td class="num">${u?m(u.kullanimBasinaUcret):"—"}</td><td><div>${i(users)} / ${i(capacity)}</div><div class="progress"><i style="width:${ratio}%"></i></div></td><td class="num">${u?n(u.urunKalitesi):"—"}</td><td class="num">${u?n(u.urunMemnuniyeti):"—"}</td><td class="num good">${u?m(u.toplamGelir):"—"}</td><td>${(app.desteklenenProtokoller||[]).map(x=>chip(x)).join("")||"—"}</td></tr>`}).join("")}
function renderTopApps(list){const active=list.filter(x=>x.urun).sort((a,b)=>Number(b.urun?.aktifKullaniciSayisi||0)-Number(a.urun?.aktifKullaniciSayisi||0)).slice(0,8);const el=document.getElementById("topApps");el.innerHTML=active.length?`<table><thead><tr><th>Uygulama</th><th>Şirket</th><th class="num">Abone</th><th class="num">Gelir</th></tr></thead><tbody>${active.map(x=>`<tr><td>${esc(x.uygulama?.uygulamaAdi)}</td><td>${esc(x.sirketAdi)}</td><td class="num">${i(x.urun?.aktifKullaniciSayisi)}</td><td class="num good">${m(x.urun?.toplamGelir)}</td></tr>`).join("")}</tbody></table>`:'<div class="empty">Henüz ticari uygulama yayını yok.</div>'}
function renderProtocols(list){const body=document.getElementById("protocolsBody");if(!list.length){body.innerHTML='<tr><td colspan="9" class="empty">Özel protokol yok.</td></tr>';return}body.innerHTML=list.map(x=>{const p=x.teknikProtokol||{};return `<tr><td><div class="name">${esc(p.protokolAdi||p.protokolKimligi)}</div><div class="small">${esc(p.protokolKimligi)}</div></td><td>${esc(x.sirketAdi)}</td><td>${esc(p.surum||"—")}</td><td><div>${esc(p.semaKimligi||"—")}</div><div class="small">${esc(p.semaOzeti||"")}</div></td><td class="${x.gecerli?"good":"bad"}">${x.gecerli?"GEÇERLİ":"EKSİK"}</td><td class="${x.piyasada?"good":"muted"}">${x.piyasada?"LİSANSLANABİLİR":"8090 BEKLİYOR"}</td><td>${(p.yetkinlikler||[]).map(y=>chip(`${y.yetkinlikKimligi} → ${y.hizmetKimligi}`)).join("")}</td><td>${(p.uyumluProtokoller||[]).map(y=>chip(y)).join("")||"—"}</td><td>${esc(x.piyasaProtokolKimligi||"—")}</td></tr>`}).join("")}
function renderServices(list){const body=document.getElementById("servicesBody");if(!list.length){body.innerHTML='<tr><td colspan="10" class="empty">Hizmet yok.</td></tr>';return}body.innerHTML=list.map(s=>`<tr><td><div class="name">${esc(s.hizmetKimligi)}</div><div class="small">v${esc(s.hizmetSurumu)} · ${esc(s.aciklama||"")}</div></td><td class="${s.aktif?"good":"bad"}">${s.aktif?"AKTİF":"KAPALI"}</td><td class="num">${i(s.talepSayisi)}</td><td class="num ${Number(s.kotuNiyetliTalepSayisi)>0?"bad":""}">${i(s.kotuNiyetliTalepSayisi)}</td><td class="num">${n(s.ortalamaZorlukSeviyesi)}</td><td class="num">${m(s.toplamTalepButcesi)}</td><td class="num good">${s.enUcuzFiyat==null?"—":m(s.enUcuzFiyat)}</td><td class="num">${s.enPahaliFiyat==null?"—":m(s.enPahaliFiyat)}</td><td class="num">${i(s.saglayiciSayisi)}</td><td>${(s.saglayicilar||[]).map(x=>chip(`${x.sirketAdi} ${m(x.birimFiyat)} · K${n(x.kodKalitesiPuani)} P${n(x.performansPuani)} G${n(x.guvenlikPuani)}`,x.bagli?"good":"bad")).join("")||'<span class="bad">Sağlayıcı yok</span>'}</td></tr>`).join("")}
function renderFinance(list){const body=document.getElementById("financeBody");body.innerHTML=[...list].sort((a,b)=>Number(b.isletim?.sirketDegeri||0)-Number(a.isletim?.sirketDegeri||0)).map(c=>{const o=c.isletim||{};return `<tr><td class="name">${esc(c.sirketAdi)}</td><td class="num good">${m(o.sirketDegeri)}</td><td class="num">${m(o.tahminiHisseFiyati)}</td><td class="num">${m(c.kasa)}</td><td class="num ${Number(o.toplamBorc)>0?"warn":""}">${m(o.toplamBorc)}</td><td class="num">${i(o.krediNotu)}</td><td class="num good">${m(o.toplamAbonelikGeliri)}</td><td class="num good">${m(o.toplamUrunGeliri)}</td><td class="num bad">${m(o.toplamIsletmeGideri)}</td><td class="num bad">${m(o.toplamFinansmanGideri)}</td></tr>`}).join("")}
function renderCredits(list){const body=document.getElementById("creditsBody");const credits=list.filter(x=>x.kredi);body.innerHTML=credits.length?credits.map(x=>{const k=x.kredi;return `<tr><td>${esc(x.sirketAdi)}</td><td>${esc(k.krediTuru)}</td><td class="num">${m(k.anaPara)}</td><td class="num warn">${m(k.kalanBorc)}</td><td class="num">${m(k.taksitTutari)}</td><td class="num">${i(k.kalanTaksit)}</td><td class="num">${pct(Number(k.tickFaizOrani||0)*100)}</td><td class="num ${Number(k.gecikmeSayisi)>0?"bad":""}">${i(k.gecikmeSayisi)}</td><td class="${k.aktif?"warn":"good"}">${k.aktif?"AKTİF":"KAPANDI"}</td></tr>`}).join(""):'<tr><td colspan="9" class="empty">Kredi kaydı yok.</td></tr>'}
function renderContracts(list){const body=document.getElementById("contractsBody");body.innerHTML=list.length?list.map(x=>{const s=x.sozlesme;return `<tr><td>${esc(x.sirketAdi)}</td><td><div class="name">${esc(s.baslik)}</div><div class="small">${esc(s.sozlesmeKimligi)}</div></td><td>${esc(s.kategori)}</td><td>${i(s.baslangicTicki)}–${i(s.bitisTicki)}</td><td class="num good">${m(s.tickOdemesi)}</td><td class="num bad">${m(s.ihlalCezasi)}</td><td class="num">${i(s.basariliTickSayisi)}</td><td class="num ${Number(s.ihlalSayisi)>0?"bad":""}">${i(s.ihlalSayisi)}</td><td class="${s.aktif?"good":"muted"}">${s.aktif?"AKTİF":"BİTTİ"}</td></tr>`}).join(""):'<tr><td colspan="9" class="empty">Aktif veya geçmiş SLA yok.</td></tr>'}
function renderInvestments(list){const body=document.getElementById("investmentsBody");const active=list.filter(x=>Number(x.seviye)>0).sort((a,b)=>a.sirketAdi.localeCompare(b.sirketAdi,"tr")||Number(b.seviye)-Number(a.seviye));body.innerHTML=active.length?active.map(x=>`<tr><td>${esc(x.sirketAdi)}</td><td>${esc(x.yatirimTuru)}</td><td class="num good">${i(x.seviye)}</td></tr>`).join(""):'<tr><td colspan="3" class="empty">Henüz yatırım yapılmadı.</td></tr>'}
function renderSecurity(list){const body=document.getElementById("securityBody");body.innerHTML=[...list].sort((a,b)=>Number(b.guvenlikPuani)-Number(a.guvenlikPuani)).map(c=>{const risk=Number(c.guvenlikPuani)>=80?"DÜŞÜK":Number(c.guvenlikPuani)>=55?"ORTA":"YÜKSEK";return `<tr><td class="name">${esc(c.sirketAdi)}</td><td class="num ${risk==="DÜŞÜK"?"good":risk==="YÜKSEK"?"bad":"warn"}">${n(c.guvenlikPuani)}</td><td class="num">${n(c.kodKalitesiPuani)}</td><td class="num good">${i(c.engellenenSaldiriSayisi)}</td><td class="num ${Number(c.basariliSaldiriSayisi)>0?"bad":""}">${i(c.basariliSaldiriSayisi)}</td><td class="num bad">${m(c.toplamGuvenlikKaybi)}</td><td class="${risk==="DÜŞÜK"?"good":risk==="YÜKSEK"?"bad":"warn"}">${risk}</td></tr>`}).join("")}
function renderSummary(o){document.getElementById("tickSummary").innerHTML=[metric("Talep",i(o.toplamTalepSayisi)),metric("Başarılı",i(o.basariliIsSayisi),"good"),metric("Başarısız",i(o.basarisizIsSayisi),Number(o.basarisizIsSayisi)>0?"bad":""),metric("Şüpheli",i(o.kotuNiyetliIsSayisi),Number(o.kotuNiyetliIsSayisi)>0?"warn":""),metric("Engellenen",i(o.engellenenSaldiriSayisi),"good"),metric("Saldırı başarılı",i(o.basariliSaldiriSayisi),Number(o.basariliSaldiriSayisi)>0?"bad":""),metric("Ciro",m(o.toplamCiro),"good"),metric("Başarı",pct(o.basariOrani)),metric("Zaman aşımı",i(o.zamanAsimiSayisi),Number(o.zamanAsimiSayisi)>0?"bad":"")].join("")}
function renderLogs(list){const el=document.getElementById("logs"),near=el.scrollHeight-el.scrollTop-el.clientHeight<80;el.innerHTML=list.map(x=>`<div class="logline"><span class="muted">${new Date(x.zaman).toLocaleTimeString("tr-TR")}</span><span class="level ${esc(x.seviye)}">${esc(x.seviye)}</span><span>${esc(x.mesaj)}</span></div>`).join("")||'<div class="empty">Motor olayı yok.</div>';if(near)el.scrollTop=el.scrollHeight}
function updateHistory(list){const now=Date.now();list.forEach(c=>{if(!S.history.has(c.sirketKimligi))S.history.set(c.sirketKimligi,{name:c.sirketAdi,value:[],cash:[]});const h=S.history.get(c.sirketKimligi);h.name=c.sirketAdi;h.value.push({x:now,y:Number(c.isletim?.sirketDegeri||0)});h.cash.push({x:now,y:Number(c.kasa||0)});if(h.value.length>120)h.value.shift();if(h.cash.length>120)h.cash.shift()})}
function drawChart(){const canvas=document.getElementById("chart"),rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,rect.width*dpr);canvas.height=Math.max(1,rect.height*dpr);const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,p={l:58,r:16,t:15,b:34};ctx.clearRect(0,0,w,h);const series=[...S.history.values()].filter(x=>x.value.length);const values=series.flatMap(x=>x.value.map(y=>y.y));let min=Math.min(0,...values),max=Math.max(1,...values);if(min===max)max=min+1;ctx.strokeStyle="#20304a";ctx.fillStyle="#8093af";ctx.font="9px Segoe UI";for(let k=0;k<=4;k++){const y=p.t+(h-p.t-p.b)*k/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillText(n(max-(max-min)*k/4),3,y+3)}series.forEach((s,index)=>{ctx.strokeStyle=color(index);ctx.lineWidth=2;ctx.beginPath();s.value.forEach((pt,j)=>{const x=p.l+(w-p.l-p.r)*(s.value.length<=1?0:j/(s.value.length-1)),y=p.t+(h-p.t-p.b)*(1-(pt.y-min)/(max-min));j?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=color(index);ctx.fillRect(p.l+index*140,h-17,10,3);ctx.fillStyle="#bdcbe0";ctx.fillText(s.name,p.l+14+index*140,h-13)})}
async function refresh(){try{const r=await fetch(`/api/durum?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();render(data);document.getElementById("dot").className="dot ok";text("connection","CANLI")}catch(error){document.getElementById("dot").className="dot bad";text("connection","BAĞLANTI YOK");console.error(error)}}
document.querySelectorAll(".tab").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));button.classList.add("active");document.getElementById(button.dataset.page).classList.add("active");drawChart()}));setInterval(()=>text("clock",new Date().toLocaleTimeString("tr-TR")),250);setInterval(refresh,1000);window.addEventListener("resize",drawChart);refresh();
</script>
</body>
</html>
""";
}
